In [35]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By

navegador = webdriver.Chrome()
navegador.get("https://www.rpachallenge.com/")

table = pd.read_excel("challenge.xlsx")

In [36]:
navegador.find_element(By.XPATH, '/html/body/app-root/div[2]/app-rpa1/div/div[1]/div[6]/button').click()
for i, first_name in enumerate(table["First Name"]):
    last_name = table.loc[i, "Last Name"]
    company_name = table.loc[i, "Company Name"]
    role = table.loc[i, "Role in Company"]
    address = table.loc[i, "Address"]
    email = table.loc[i, "Email"]
    phone_number = table.loc[i, "Phone Number"]
    # Preencher Company Name
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelCompanyName"]').send_keys(company_name)
    # Preencher Phone Number
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelPhone"]').send_keys(str(phone_number))
    # Preencher Email
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelEmail"]').send_keys(email)
    # Preencher Role in Company
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelRole"]').send_keys(role)
    # Preencher Last Name
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelLastName"]').send_keys(last_name)
    # Preencher Address
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelAddress"]').send_keys(address)
    # Preencher First Name
    navegador.find_element(By.CSS_SELECTOR, '[ng-reflect-name="labelFirstName"]').send_keys(first_name)
    # Enviar formul√°rio
    navegador.find_element(By.XPATH, '/html/body/app-root/div[2]/app-rpa1/div/div[2]/form/input').click()

In [18]:
display(table)

,First Name,Last Name,Company Name,Role in Company,Address,Email,Phone Number
0,John,Smith,IT Solutions,Analyst,98 North Road,jsmith@itsolutions.co.uk,40716543298
1,Jane,Dorsey,MediCare,Medical Engineer,11 Crown Street,jdorsey@mc.com,40791345621
2,Albert,Kipling,Waterfront,Accountant,22 Guild Street,kipling@waterfront.com,40735416854
3,Michael,Robertson,MediCare,IT Specialist,17 Farburn Terrace,mrobertson@mc.com,40733652145
4,Doug,Derrick,Timepath Inc.,Analyst,99 Shire Oak Road,dderrick@timepath.co.uk,40799885412
5,Jessie,Marlowe,Aperture Inc.,Scientist,27 Cheshire Street,jmarlowe@aperture.us,40733154268
6,Stan,Hamm,Sugarwell,Advisor,10 Dam Road,shamm@sugarwell.org,40712462257
7,Michelle,Norton,Aperture Inc.,Scientist,13 White Rabbit Street,mnorton@aperture.us,40731254562
8,Stacy,Shelby,TechDev,HR Manager,19 Pineapple Boulevard,sshelby@techdev.com,40741785214
9,Lara,Palmer,Timepath Inc.,Programmer,87 Orange Street,lpalmer@timepath.co.uk,40731653845